### ISSUE TITLE
Enable more GitHub-like options in HTML rendering.

### ISSUE THREAD

**Issue by dbernheisel** [intrvertmichael/markdown-tab#1]
Heyo, thanks for publishing this. It looks great.

I gave it a spin and there's a couple of missing features of markdown that I use and would appreciate using in this Chrome extension. I see that this is using Showdown to convert the input into rendered HTML.

- task lists (like `- [ ] task one` for pending and `- [x] task one` for done)
- simplifiedAutoLink (auto-linking URLs like `https://www.google.com` and it auto-linking instead of having to type out `[https://www.google.com](https://www.google.com)`
- strikethrough (supporting `~~strikethrough text~~`)
- tables
- ghCodeBlocks (fenced code w/ syntax highlighting)
- Generally, I prefer the GitHub-flavored Markdown which Showdown supports. I won't suggest you should change this extension to use GFM absolutely, but it would be wonderful to have the option to use it.

Above are options that could be opted-into in Showdown. Currently, no options are supplied so everything is using Showdown defaults. I'm _hoping_ it wouldn't be too much trouble to enable some of these suggested options above, or even better, providing a stored setting to allow users to pass these options in.

I've never developed a Chrome extension before, but I'll be happy to provide a PR to tackle some of these if you agree with the suggestions above.

**Comment by intrvertmichael** [comment]
hey whats up man, sorry just saw this message. 

I will definitely try to implement those changes. I don't know how to do all of those things but I will look into it and add it as I figure it out. I'm currently working on another project but once I finish that [~2 weeks] I will update this. Been wanting to with new things i've learned.

If you want to add to it I would definitely appreciate it and add it on

**Comment by dbernheisel** [comment]
Thanks for considering it! 

I [forked and essentially re-wrote it](https://github.com/dbernheisel/markdowntab) using Vue, markdown-it, and Tailwind CSS. I wanted to learn more about developing in those frameworks so I did it for my own enjoyment. 

[I have a branch](https://github.com/dbernheisel/MarkdownTab/tree/db-more-gfm?files=1) that I could submit back to this repo, but don't do it just for me.

**Comment by intrvertmichael** [comment]
In general those were good ideas and good ways to upgrade the project. I’ve just been trying to learn other things since then haven’t given it the time. It needs a revisit.

Thank you for the suggestions. Definitely will come back to this

**Comment by intrvertmichael** [comment]
Hey, I just finished updating and republishing the extension. I added all the features you suggested by using markdown-it which you also suggested. With some research I found that it's the most popular markdown parser. I also remade it in React so it's easier to update.

Thanks for the suggestions.
I'm going to close this issue now.
